# Generated by Django 5.1.6 on 2025-02-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
