# Generated by Django 5.1.6 on 2025-02-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_review_genre_bookrecommendation_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='usertype',
            field=models.CharField(blank=True, default='user', max_length=255, null=True),
        ),
    ]
