# Generated by Django 5.1.6 on 2025-03-06 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_login_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrecommendation',
            name='bookcoverimage',
            field=models.FileField(blank=True, null=True, upload_to='bookcoverimage'),
        ),
    ]
