# Generated by Django 5.1.6 on 2025-03-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_bookrecommendation_bookcoverimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuzzleGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
