# Generated by Django 5.1.6 on 2025-03-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_puzzlegame'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='book',
        ),
        migrations.AddField(
            model_name='review',
            name='bookname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
